#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KnockKnockScreen.Resource", IsApplication=true)]

namespace KnockKnockScreen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Knock = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int PowerOff = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PowerOn = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int BtnStartService = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int DeveloperName = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int MainLayout = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int openCloseText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int statusText = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int versionText = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int warningText = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ımageView1 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Active = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int ClickToClose = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int ClickToOpen = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Developer = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int NotifText = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int Passive = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int StartService = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int StopService = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int Warning = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
